name: GitHub Actions Demo
on: [push]
jobs:
  api-diff:
    name: Check API diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Comment pull request with API diff
        uses: atirnayab/test-ci-cd@test
        with:
          file: doc/api.yml
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
