name: GitHub Actions Demo
on: [push]
jobs:
  api-diff:
    name: Check API diff
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo ${{github.token}}
      - run: echo ${{secrets.GITHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Comment pull request with API diff
        uses: atirnayab/test-ci-cd@main
        with:
          doc: doc/api.yml
          token: ${{secrets.GITHUB_TOKEN}}
          file: doc/api.yml
        env:
          GITHUB_TOKEN: ${{ github.token }}
