name: GitHub Actions Demo
on: [push]
jobs:
  update-doc:
    name: update theneo doc
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: process documentation on server
        uses: atirnayab/test-ci-cd@main
        with:
          doc: doc/api.yml
          key: ${{secrets.KEY}}
          secret: ${{secrets.SECRET}}
