name: GitHub Actions Demo
on: [push]
jobs:
  api-diff:
    name: Check API diff
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
      - name: Comment pull request with API diff
        with:
          doc: "doc/api.yml"
          token: "asdfdasfdas"
          file: doc/api.yml
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
