name: GitHub Actions Demo
on: [push]
jobs:
  update-doc:
    name: update theneo doc
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
      - name: upload file to server
        uses: atirnayab/test-ci-cd@test
        with:
          doc: doc/api.yml
          key: ${{secrets.KEY}}
          secret: ${{secrets.SECRET}}
